# Generated by Django 5.2 on 2025-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
