# Generated by Django 5.2 on 2025-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuitem_named_url_remove_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
