# Generated by Django 5.2 on 2025-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_remove_menu_slug_menuitem_named_url_menuitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
