# Generated by Django 5.2 on 2025-04-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='url',
            new_name='urls',
        ),
    ]
