# Generated by Django 5.2 on 2025-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_url_menuitem_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='urls',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
